apiVersion: v1
kind: Namespace
metadata:
  name: csserver
  labels:
    app.kubernetes.io/name: csserver
    app.kubernetes.io/part-of: csserver
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecrets.name }}
  namespace: csserver
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: csserver-app
  namespace: csserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: csserver-app
    spec:
      containers:
      - name: csserver-deployment
        image: {{ .Values.image.repository }}/csserver:{{ .Values.image.tag }}
        ports:
        - containerPort: 27005
          protocol: UDP
          name: csport27005
        - containerPort: 27015
          protocol: UDP
          name: csport27015
        - containerPort: 1200
          protocol: UDP
          name: csport1200
        env:
        - name: TITLE
          value: {{ .Values.title }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets.name }}
          namespace: csserver
---
apiVersion: v1
kind: Service
metadata:
  name: csserver-service
  namespace: csserver
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP
  externalTrafficPolicy: Local
  ports:
  - protocol: UDP
    port: 27005
    targetPort: csport27005
    name: csport27005svc
  - protocol: UDP
    port: 27015
    targetPort: csport27015
    name: csport27015svc
  - protocol: UDP
    port: 1200
    targetPort: csport1200
    name: csport1200svc
  selector:
    app: csserver-app